import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { useAuth } from '../hooks/useAuth'
import { Calendar, Camera, Link2, TrendingUp, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'

export default function Dashboard() {
  const { profile, user, isAdmin } = useAuth()
  const [stats,setStats]=useState({schedule:0,attendance:0,links:0,compliance:0})
  useEffect(()=>{let live=true;async function load(){const now=new Date();const start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;const end=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${new Date(now.getFullYear(),now.getMonth()+1,0).getDate()}`;const [s,a,l]=await Promise.all([supabase.from('schedules').select('id',{count:'exact',head:true}).eq('user_id',user.id).gte('schedule_date',start).lte('schedule_date',end),supabase.from('attendance').select('id',{count:'exact',head:true}).eq('user_id',user.id).gte('attendance_date',start).lte('attendance_date',end),supabase.from('content_links').select('id',{count:'exact',head:true}).eq('user_id',user.id).gte('link_date',start).lte('link_date',end)]);if(live)setStats({schedule:s.count||0,attendance:a.count||0,links:l.count||0,compliance:Math.min(100,Math.round((l.count||0)/Math.max(1,(s.count||0)*3)*100))})}if(user?.id)load();return()=>{live=false}},[user?.id])
  const cards=[{label:'Jadwal Bulan Ini',value:stats.schedule,icon:Calendar,color:'from-blue-500 to-blue-600',to:'/jadwal-saya'},{label:'Absensi Bulan Ini',value:stats.attendance,icon:Camera,color:'from-emerald-500 to-emerald-600',to:'/absensi'},{label:'Link Terlapor',value:stats.links,icon:Link2,color:'from-amber-500 to-orange-600',to:'/upload-link'},{label:'Kepatuhan Link',value:`${stats.compliance}%`,icon:TrendingUp,color:'from-purple-500 to-pink-600',to:isAdmin?'/admin/reports':'/upload-link'}]
  return <div className="space-y-6"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="card bg-gradient-to-br from-brand-600 to-blue-800 text-white border-none"><p className="text-blue-100 text-sm mb-1">JADWAL KERJA · KREDIVO iBOX BINTARO</p><h1 className="text-2xl font-extrabold mb-2">Selamat datang, {profile?.full_name||'Tim Bintaro'}</h1><p className="text-blue-100 text-sm">{isAdmin?'Kelola anggota, susun jadwal sebar, dan pantau laporan tim.':'Pantau jadwal, kirim absensi, dan lengkapi laporan link sebar hari ini.'}</p></motion.div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{cards.map((s,i)=>{const Icon=s.icon;return <motion.div key={s.label} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} className="card"><div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${s.color} flex items-center justify-center mb-3 shadow-md`}><Icon className="w-5 h-5 text-white"/></div><p className="text-xs text-slate-400 font-medium">{s.label}</p><p className="text-2xl font-extrabold text-slate-800 mt-0.5">{s.value}</p><Link to={s.to} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-brand-700">Buka <ArrowRight size={13}/></Link></motion.div>})}</div><div className="grid md:grid-cols-2 gap-4">{(isAdmin?[{title:'Kelola anggota',desc:'Perbarui profil, tim, dan status anggota.',to:'/admin/members'},{title:'Generate jadwal',desc:'Susun jadwal bulanan dan hari libur.',to:'/admin/schedule'},{title:'Laporan tim',desc:'Pantau absensi, link, KPI, dan reminder WhatsApp.',to:'/admin/reports'}]:[{title:'Jadwal saya',desc:'Lihat tugas toko atau sebar yang diberikan admin.',to:'/jadwal-saya'},{title:'Kirim absensi',desc:'Kirim foto dan lokasi dengan izin perangkat.',to:'/absensi'},{title:'Upload link',desc:'Laporkan link Facebook, Instagram, TikTok, OLX, atau Threads.',to:'/upload-link'}]).map(x=><Link key={x.to} to={x.to} className="card flex items-center justify-between gap-4 hover:border-brand-200 hover:shadow-md transition"><div><h2 className="font-bold text-slate-800">{x.title}</h2><p className="text-sm text-slate-500 mt-1">{x.desc}</p></div><ArrowRight className="text-brand-600 shrink-0"/></Link>)}</div></div>
}
